# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8sSQjkxxaJn3qshdHnGbkcHDQIkOpfP
"""

import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

for cell in a.flat:
  print(cell)

for x in np.nditer(a, order='F', flags=['external_loop']):
  print(x)

print(a)

for x in np.nditer(a, op_flags = ['readwrite']):
  x[...] = x*x
print(a)

b = np.arange(5, 20, 5).reshape(3, 1)
print(b)

for x, y in np.nditer([a, b]):
  print(x, y)