# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHgrf537mdYgr3gQb5bmxMDUx8s4-rLR
"""

import pandas as pd

df = pd.read_csv("netflix_titles_nov_2019.csv", na_values = ['nan'])
df

df.head(5)

df.tail(3)

df.shape

df.sample(4)

df[2:5]

df['rating']

dir(df.rating)

df['release_year'].min(), df.release_year.max(), df['release_year'].mean()

after_2010 = df[df.release_year > 2010].sample(5)
before_2010 = df[df.release_year < 2010].sample(5)

after_2010

before_2010

df[1:10]

movies_df = len(df[df['type'] == 'Movie'])
tvshows_df = len(df[df.type == 'TV Show'])

print(f"The dataset contains {movies_df} movies and {tvshows_df} TV shows.")

df.columns

df.rating.unique()

df.type.nunique()

df.type.value_counts()

df_new = df[["title", "director", "rating", "type"]]
df_new

df_new.shape

df_data = df[(df.release_year > 2015) & (df.rating == 'R')]
df_data

df.describe()

df.info()

df[(df.release_year == df.release_year.max()) | (df.release_year == df.release_year.min())]

df['age'] = df.release_year.apply(lambda x: 2025 - x)
df.sample (4)

df.index

df.set_index("title", inplace=True)
df.head(4)

df.index

df.loc["Chip and Potato"]

df.iloc[2:6]

df.reset_index(inplace=True)

df.tail(5)

df.info()

df.rating.unique()

df_new['age'] = df['age']
df_new

# df_new.to_csv('movies.csv', index=False)